version: '2'
volumes:
  gitlab-app-data:
    driver: ${volumedriver}
  gitlab-log-data:
    driver: ${volumedriver}
  gitlab-conf-files:
    driver: ${volumedriver}

services:
  gitlab-server:
    ports:
      - 22:22/tcp
      - 81:80/tcp
      - 8443:443/tcp
    labels:
      io.rancher.container.hostname_override: container_name
    image: gitlab/gitlab-ce:9.3.3-ce.0
    volumes:
      - gitlab-app-data:/var/opt/gitlab
      - gitlab-log-data:/var/log/gitlab
      - gitlab-conf-files:/etc/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${gitlab_omnipus_prefix}${gitlab_hostname}'
        registry_external_url '${gitlab_omnipus_prefix}${registry_gitlab_hostname}'
  jenkins-primary:
    image: "jenkins:2.60.1"
    ports:
      - "8081:8080"
    labels:
      io.rancher.sidekicks: jenkins-plugins,jenkins-datavolume
      io.rancher.container.hostname_override: container_name
    volumes_from:
      - jenkins-plugins
      - jenkins-datavolume
    entrypoint: /usr/share/jenkins/rancher/jenkins.sh
  jenkins-plugins:
    image: rancher/jenkins-plugins:v0.1.1
  jenkins-datavolume:
    image: "busybox"
    volumes:
      - ${volume_work}:/var/jenkins_home
    labels:
      io.rancher.container.start_once: true
    entrypoint: ["chown", "-R", "1000:1000", "/var/jenkins_home"]
  che:
    image: eclipse/che-server:5.0.0-latest
    ports: 
      - 8082:8080
    environment:
      CHE_LOCAL_CONF_DIR=/C/conf
      CHE_ASSEMBLY=/home/my_assembly
      DOCKER_MACHINE_HOST=172.20.0.1
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
