version: '2'
volumes:
  gitlab-app-data:
    driver: ${volumedriver}
  gitlab-log-data:
    driver: ${volumedriver}
  gitlab-conf-files:
    driver: ${volumedriver}

services:
  gitlab-server:
    ports:
      - 22:22/tcp
    labels:
      io.rancher.container.hostname_override: container_name
      traefik.enable: true
      traefik.port: 80
      traefik.domain: cloud.spicter.com
      traefik.alias: git
    image: gitlab/gitlab-ce:9.3.3-ce.0
    volumes:
      - gitlab-app-data:/var/opt/gitlab
      - gitlab-log-data:/var/log/gitlab
      - gitlab-conf-files:/etc/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${gitlab_omnipus_prefix}${gitlab_hostname}'
        registry_external_url '${gitlab_omnipus_prefix}${registry_gitlab_hostname}'
  jenkins-primary:
    image: "jenkins:2.60.1"
    labels:
      io.rancher.sidekicks: jenkins-plugins,jenkins-datavolume
      io.rancher.container.hostname_override: container_name
      traefik.enable: true
      traefik.port: 8080
      traefik.domain: cloud.spicter.com
      traefik.alias: jenkins
    volumes_from:
      - jenkins-plugins
      - jenkins-datavolume
    entrypoint: /usr/share/jenkins/rancher/jenkins.sh
  jenkins-plugins:
    image: rancher/jenkins-plugins:v0.1.1
  jenkins-datavolume:
    image: "busybox"
    volumes:
      - ${volume_work}:/var/jenkins_home
    labels:
      io.rancher.container.start_once: true
    entrypoint: ["chown", "-R", "1000:1000", "/var/jenkins_home"]
  che:
    image: eclipse/che-server:5.0.0-latest
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    labels:
      io.rancher.sidekicks: che-data
      traefik.enable: true
      traefik.port: 8080
      traefik.domain: cloud.spicter.com
      traefik.alias: ide
    volumes_from:
      - che-data
  che-data:
    image: busybox
    labels:
      io.rancher.container.start_once: true
    volumes:
        - /opt/che/data:/data
  openproject:
    image: openproject/community:7
    volumes_from:
      - openproject-data
    labels:
      io.rancher.sidekicks: openproject-data
      io.rancher.container.hostname_override: container_name
      traefik.enable: true
      traefik.port: 80
      traefik.domain: cloud.spicter.com
      traefik.alias: project
  openproject-data:
    image: openproject/community:7
    entrypoint:
      - /bin/true
    volumes:
      - /var/lib/postgresql/9.4/main
      - /var/log/supervisor
      - /var/db/openproject
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
  sonarqube-data:
    image: busybox
    labels:
      io.rancher.container.start_once: true
    volumes:
        - /opt/sonarqube/extensions/plugins
  sonarqube:
    image: sonarqube
    links:
        - postgres
    environment:
        SONARQUBE_JDBC_USERNAME: root
        SONARQUBE_JDBC_PASSWORD: test-password
        SONARQUBE_JDBC_URL: jdbc:postgresql://postgres/sonar
    labels:
      io.rancher.sidekicks: sonarqube-data
      traefik.enable: true
      traefik.port: 9000
      traefik.domain: cloud.spicter.com
      traefik.alias: sonar
    volumes_from:
        - sonarqube-data        

  postgres-data:
    image: busybox
    labels:
      io.rancher.container.start_once: true
    volumes:
        - /var/lib/postgresql/data/pgdata

  postgres:
    image: postgres:latest
    ports:
        - 5432:5432
    environment:
        PGDATA: /var/lib/postgresql/data/pgdata
        POSTGRES_DB: sonar
        POSTGRES_USER: root
        POSTGRES_PASSWORD: test-password
    tty: true
    stdin_open: true
    labels:
        io.rancher.sidekicks: postgres-data
    volumes_from:
        - postgres-data
