name: Data Mangement
description: |
  a CQRS based solution which seemless integrates SQL/JPA, Graph-, timeseries-, bigdata- stores behind an easy to use, standard based API
version: v0.0.1
category: Databases
