.catalog:
  name: netdata
  version: v1.0.0
  description: API Management, done right!
dreamfactory:
  scale: 1
  start_on_create: true
  health_check:
    port: 80
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2
